### ISSUE TITLE
Where does the plugin look for config.json

### ISSUE THREAD

**Issue by maersdal** [suoto/hdl_checker_vscode#2]
I'm trying to configure the plugin, but it seems I've put the config.json in the wrong location.
What is the correct location for a project-specific config.json ?

Regards.

**Comment by suoto** [comment]
The VS Code extension's only config is a path that will be added to the system path so you can add tools.

Other HDL Checker specific configs are set through `.hdl_checker.config` (on Linux) or `_hdl_checker.config` (on Windows), which is placed in the project's root directory. There's more info in HDL Checker wiki: https://github.com/suoto/hdl_checker/wiki/HOWTO:-Setting-up-a-project

Let me know if that helps!

**Comment by maersdal** [comment]
I got the detection of the config file working now.
What I did wrong was to place it in
`project_dir/_hdl_checker/config.json`
instead of the proper path
`project_dir/_hdl_checker.config`
I have to delete the cache file to properly see my changes.
Next issue is that entities declared with work.myentity are not recognized. But I hope to figure that out today.
Thanks.
